name: KERNEL BUILDER
on:
  workflow_dispatch:
    inputs:
      name:
        description: '〩Beler'
        default: 'kernel-4.9'
        required: true
        type: string
      compiler:
        description: 'Kompiler | gcc|clang|llvm|other|gcc2|clang2|llvm2'
        default: 'clang'
        required: true
        type: string
      aosp-clang:
        description: 'Versi Clang | false | 11 | 13 | 14 | 19 | 20 | 21 | 22'
        default: '11'
        required: true
        type: string
      package:
        description: 'Paket lainnya|gcc2|clang2|llvm2'
        default: 'sudo apt-get install --no-install-recommends -y clang gcc gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu libffi-dev libncurses5-dev libreadline-dev libsqlite3-dev pigz libarchive-tools software-properties-common openssl ssh wget nano ca-certificates zstd cpio lld llvm g++-aarch64-linux-gnu libelf-dev neofetch'
        required: true
        type: string
      command:
        description: 'Perintah lainnya|gcc2|clang2|llvm2'
        default: 'LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar HOSTLD=ld.lld'
        required: true
        type: string
      kernel-url:
        description: 'URL Kernel'
        default: 'https://github.com/awangunawan12332122-lab/Xiaomi_Kernel_OpenSource.git'
        required: true
        type: string
      kernel-branch:
        description: 'Cabang Kernel'
        default: 'dipper-q-oss'
        required: true
        type: string
      kernel-config:
        description: 'Konfigurasi Kernel'
        default: 'beryllium_defconfig'
        required: true
        type: string
      kernelsu:
        description: 'KernelSU-Next | false jika sumber tidak kompatibel'
        default: 'curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s legacy'
        required: true
        type: string
      disable-lto:
        description: 'Nonaktifkan LTO'
        default: 'true'
        required: true
        type: string
jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
    - name: Pemeriksaan awal
      run: |
         echo "nama: ${{ inputs.name }}"
         echo "kompiler: ${{ inputs.compiler }}"
         echo "aosp-clang: ${{ inputs.aosp-clang }}"
         if [ "${{ inputs.compiler }}" == "other" ]; then
            echo "paket: ${{ inputs.package }}"
            echo "perintah: ${{ inputs.command }}"
         fi
         if [ "${{ inputs.kernel-url }}" != "false" ]; then
            echo "url-kernel: ${{ inputs.kernel-url }}"
            echo "cabang-kernel: ${{ inputs.kernel-branch }}"
         fi
         if [ "${{ inputs.kernel-url }}" == "false" ]; then
            echo "url-kernel: gunakan repo saat ini"
            if [ "${{ inputs.kernel-branch }}" != "main" ]; then
               echo "custom-sc: ${{ inputs.kernel-branch }}"
            fi
            if [ "${{ inputs.kernel-branch }}" == "main" ]; then
               echo "custom-sc: dinonaktifkan"
            fi
         fi
         echo "konfigurasi-kernel: ${{ inputs.kernel-config }}"
         echo "kernelsu: ${{ inputs.kernelsu }}"
         echo "nonaktifkan-lto: ${{ inputs.disable-lto }}"
         echo "Proyek builder"
         
    - name: Mengosongkan ruang penyimpanan
      run: |
         echo "Membersihkan sisa file sistem untuk menambah ruang disk..."
         sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
         sudo docker image prune --all --force
         sudo apt-get clean
         echo "Sisa ruang penyimpanan saat ini:"
         df -h
         
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Mempersiapkan paket dan memori swap
      run: |
         sudo swapoff /swapfile || true
         sudo rm -f /swapfile
         sudo fallocate -l 8G /swapfile
         sudo chmod 600 /swapfile
         sudo mkswap /swapfile
         sudo swapon /swapfile
         
         sudo apt-get update
         sudo apt-get install --no-install-recommends -y binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python3 python-is-python3 aria2
         if [[ "${{ inputs.compiler }}" =~ ^(gcc|llvm|gcc2|llvm2)$ ]]; then
             sudo apt-get install --no-install-recommends -y clang gcc gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu libffi-dev libncurses5-dev libreadline-dev libsqlite3-dev pigz libarchive-tools software-properties-common openssl ssh wget nano ca-certificates zstd
         fi
         if [[ "${{ inputs.compiler }}" =~ ^(llvm|llvm2)$ ]]; then
             sudo apt-get install --no-install-recommends -y cpio lld llvm g++-aarch64-linux-gnu libelf-dev neofetch
         fi
         if [[ "${{ inputs.compiler }}" =~ ^(other|clang2|gcc2|llvm2)$ ]]; then
             ${{ inputs.package }}
         fi
         aria2c -q https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh && NONINTERACTIVE=1 bash ./uninstall.sh -f -q

    - name: Mempersiapkan GCC
      run: |
         if [ "${{ inputs.aosp-clang }}" == "false" ]; then
            echo "Menggunakan gcc bawaan"
         else
            mkdir -p -v $HOME/gcc-64
            aria2c -o gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/0a0604336d4d1067aa1aaef8d3779b31fcee841d.tar.gz
            tar -C $HOME/gcc-64 -zxf gcc-aarch64.tar.gz
            mkdir -p -v $HOME/gcc-32
            aria2c -o gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/4d16d93f49c2b5ecdd0f12c38d194835dd595603.tar.gz
            tar -C $HOME/gcc-32 -zxf gcc-arm.tar.gz
         fi
         
    - name: Mempersiapkan Clang
      run: |
         if [ "${{ inputs.aosp-clang }}" == "false" ]; then
            echo "Menggunakan clang bawaan"
         else
            if [ "${{ inputs.aosp-clang }}" == "11" ]; then
                aria2c -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-11.0.0_r46/clang-r383902b1.tar.gz
            elif [ "${{ inputs.aosp-clang }}" == "13" ]; then
                aria2c -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android13-release/clang-r450784d.tar.gz
            elif [ "${{ inputs.aosp-clang }}" == "14" ]; then
                aria2c -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android14-release/clang-r487747c.tar.gz
            elif [ "${{ inputs.aosp-clang }}" == "19" ]; then
                aria2c -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r530567.tar.gz
            elif [ "${{ inputs.aosp-clang }}" == "20" ]; then
                aria2c -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz
            elif [ "${{ inputs.aosp-clang }}" == "21" ]; then
                aria2c -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r552898.tar.gz
            elif [ "${{ inputs.aosp-clang }}" == "22" ]; then
                aria2c -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r576645.tar.gz
            elif [ "${{ inputs.aosp-clang }}" != "false" ]; then
                aria2c -o aosp-clang.tar.gz ${{ inputs.aosp-clang }}
            fi
            mkdir $HOME/clang -p -v
            tar -C $HOME/clang -zxf aosp-clang.tar.gz
         fi
         
    - name: Mempersiapkan Kernel
      run: |
         if [ "${{ inputs.kernel-url }}" != "false" ]; then
            git clone --depth=1 ${{ inputs.kernel-url }} -b ${{ inputs.kernel-branch }} kernel-dir
         else
            ls
         fi
         
    - name: Menonaktifkan LTO dan Mengatur Konfigurasi Kernel 4.9
      run: |
         if [ "${{ inputs.kernel-url }}" != "false" ]; then
            cd kernel-dir
         fi
         CONFIG_PATH="arch/arm64/configs/${{ inputs.kernel-config }}"
         
         # Mematikan LTO sesuai parameter input
         if [ "${{ inputs.disable-lto }}" == "true" ]; then
             if grep -q "LTO" "$CONFIG_PATH"; then
                  sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/' "$CONFIG_PATH" 
                  sed -i 's/CONFIG_LTO_CLANG=y/CONFIG_LTO_CLANG=n/' "$CONFIG_PATH" 
                  sed -i 's/CONFIG_THINLTO=y/CONFIG_THINLTO=n/' "$CONFIG_PATH" 
                  echo "CONFIG_LTO_NONE=y" | tee -a "$CONFIG_PATH" >/dev/null
             fi
         fi
         
         # FIX Khusus untuk Kernel 4.9: Mematikan Stack Protector Strong 
         sed -i 's/CONFIG_CC_STACKPROTECTOR_STRONG=y/CONFIG_CC_STACKPROTECTOR_STRONG=n/' "$CONFIG_PATH" || true
         sed -i 's/CONFIG_CC_STACKPROTECTOR=y/CONFIG_CC_STACKPROTECTOR=n/' "$CONFIG_PATH" || true
         echo "CONFIG_CC_STACKPROTECTOR_AUTO=y" | tee -a "$CONFIG_PATH" >/dev/null
         
    - name: Mempersiapkan KernelSU-Next
      run: |
         if [ "${{ inputs.kernel-url }}" != "false" ]; then
            cd kernel-dir
         fi
         
         # Install KernelSU-Next
         if [ "${{ inputs.kernelsu }}" != "false" ]; then
            rm -rf KernelSU-Next
            ${{ inputs.kernelsu }}
         fi
         
    - name: Mengkompilasi Kernel
      run: |
         mkdir out -p -v
         if [ "${{ inputs.kernel-url }}" != "false" ]; then
            cd kernel-dir
            OUT_DIR="../out"
         else
            OUT_DIR="out"
         fi
         
         chmod -R +x scripts/ || true
         
         # FIX UNTUK ERROR 'multiple definition of yylloc' PADA HOSTCC
         sed -i 's/YYLTYPE yylloc;/extern YYLTYPE yylloc;/g' scripts/dtc/dtc-lexer.lex.c_shipped 2>/dev/null || true
         sed -i 's/YYLTYPE yylloc;/extern YYLTYPE yylloc;/g' scripts/dtc/dtc-lexer.l 2>/dev/null || true
         
         if [ ! -f "scripts/min-tool-version.sh" ]; then
             echo '#!/bin/sh' > scripts/min-tool-version.sh
             echo 'case "$1" in llvm) echo 10.0.0;; clang) echo 10.0.0;; *) echo 0.0.0;; esac' >> scripts/min-tool-version.sh
             chmod +x scripts/min-tool-version.sh
         fi
         
         if [ "${{ inputs.aosp-clang }}" == "false" ]; then
            echo "Menggunakan gcc dan clang bawaan"
         else
            export PATH=$HOME/clang/bin:$HOME/gcc-64/bin:$HOME/gcc-32/bin:$PATH
         fi
         
         export KBUILD_BUILD_USER="〩Beler"
         export KBUILD_BUILD_HOST="Builder"
         
         # Perbaikan penulisan KCFLAGS agar tidak terjadi unterminated quoted string
         KCFLAGS_OPTS="-Wno-error -Wno-unknown-warning-option -Wno-initializer-overrides -Wno-pointer-sign -Wno-uninitialized"
         COMMAND="make -j$(nproc --all) O=$OUT_DIR ARCH=arm64 HOSTCFLAGS=-fcommon KCFLAGS='$KCFLAGS_OPTS'"
         
         if [ "${{ inputs.aosp-clang }}" == "false" ]; then
                COMMAND+=" CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CROSS_COMPILE_COMPAT=arm-linux-gnueabi-"
         else
                COMMAND+=" CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- CROSS_COMPILE_COMPAT=arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu-"
         fi
         
         if [ "${{ inputs.compiler }}" == "clang" ]; then
            COMMAND+=" CC=clang LLVM=1 LLVM_IAS=1"
         elif [ "${{ inputs.compiler }}" == "llvm" ]; then
            COMMAND+=" CC=clang LLVM=1 LLVM_IAS=1 AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar"
         elif [ "${{ inputs.compiler }}" == "clang2" ]; then
            COMMAND+=" CC=clang ${{ inputs.command }}"
         elif [ "${{ inputs.compiler }}" == "llvm2" ]; then
            COMMAND+=" CC=clang LLVM=1 LLVM_IAS=1 AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar ${{ inputs.command }}"
         elif [ "${{ inputs.compiler }}" == "other" ]; then
            COMMAND+=" ${{ inputs.command }}"
         fi
         
         $COMMAND ${{ inputs.kernel-config }}
         $COMMAND all
         
    - name: Membuat flashable.zip
      run: |
          git clone https://github.com/osm0sis/AnyKernel3 AnyKernel3
          rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md AnyKernel3/modules AnyKernel3/patch AnyKernel3/ramdisk
          
          if [[ -f out/arch/arm64/boot/Image.gz-dtb ]]; then
            cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb
          elif [[ -f out/arch/arm64/boot/Image-dtb ]]; then
            cp out/arch/arm64/boot/Image-dtb AnyKernel3/Image-dtb
          elif [[ -f out/arch/arm64/boot/Image.gz ]]; then
            cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
          elif [[ -f out/arch/arm64/boot/Image ]]; then
            cp out/arch/arm64/boot/Image AnyKernel3/Image
          fi
          
          if [ -f out/arch/arm64/boot/dtbo.img ]; then
            cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
          fi
          
    - name: Mengunggah hasil
      run: |
          mkdir Upload
          cp -rf AnyKernel3/* Upload
          
    - id: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.name }}"
        path: Upload/*
        
